### ISSUE TITLE
Problems with recursive reload

### ISSUE THREAD

**Issue by sdemyanov** [andersbll/deeppy#13]
Hi Anders,

Sorry for bothering, I am relatively new to Python. I have a problem: after I do changes in the code, I want to recursively reload all deeppy module, so I call "dreload(deeppy)". However, even if I don't make any changes, reload causes the next run to fail with the following error. Could you please advise anything about it?

%run "/home/sdemyanov/Server/deeppy/examples/mlp_mnist.py"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/sdemyanov/Server/deeppy/examples/mlp_mnist.py in <module>()
     62         learn_rule=dp.Momentum(learn_rate=learn_rate/10**i, momentum=0.94),
     63     )
---> 64     trainer.train(net, train_input)
     65 
     66 # Evaluate on test data

/home/sdemyanov/Server/deeppy/deeppy/train/sgd.pyc in train(self, model, input, val_error_fun)
     19     def train(self, model, input, val_error_fun=None):
     20         input = Input.from_any(input)
---> 21         model._setup(**input.shapes)
     22         params = model._params
     23         self.learn_rule.learn_rate /= input.batch_size

/home/sdemyanov/Server/deeppy/deeppy/feedforward/neural_network.pyc in _setup(self, x_shape, y_shape)
     20             return
     21         for layer in self.layers:
---> 22             layer._setup(x_shape)
     23             x_shape = layer.y_shape(x_shape)
     24         self.loss._setup(x_shape, y_shape)

/home/sdemyanov/Server/deeppy/deeppy/feedforward/layers.pyc in _setup(self, x_shape)
     39         if not self.weights.name:
     40             self.weights.name = self.name + '_w'
---> 41         self.bias._setup(self.n_out)
     42         if not self.bias.name:
     43             self.bias.name = self.name + '_b'

/home/sdemyanov/Server/deeppy/deeppy/parameter.pyc in _setup(self, shape)
     31     def _setup(self, shape):
     32         if self._array is None:
---> 33             self._array = self.filler.array(shape)
     34         else:
     35             if isinstance(shape, int):

/home/sdemyanov/Server/deeppy/deeppy/filler.pyc in array(self, shape)
     32 
     33     def array(self, shape):
---> 34         return ca.ones(shape)*self.value
     35 
     36 

/home/sdemyanov/anaconda/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-linux-x86_64.egg/cudarray/cudarray.pyc in __mul__(self, other)
    101 
    102     def __mul__(self, other):
--> 103         return elementwise.multiply(self, other)
    104 
    105     def __rmul__(self, other):

AttributeError: 'module' object has no attribute 'multiply'

**Comment by andersbll** [comment]
It looks like the libcudarray (the C library beneath CUDArray), cannot be reloaded. I believe the problem you describe is the same as [this one](http://stackoverflow.com/questions/18216906/reloading-a-python-extension-module-from-ipython). If this is the case, the problem can be solved by restarting the IPython kernel and run your code again.

**Comment by sdemyanov** [comment]
Ok, I see. Thank you for a prompt response!

**Comment by andersbll** [comment]
You're welcome :)
