### ISSUE TITLE
700th star

### ISSUE THREAD

**Issue by EderSantana** [andersbll/deeppy#14]
I don't have an issue, I just thought that was fun!
And thanks for the neural style implementation that does not blow up the memory of a K20!!!
I don't know what is wrong with the other implementations out there (or with me), but yeah, tkx!
High 5 and close this as soon as you read it!

**Comment by andersbll** [comment]
Thank you! :)

I wonder what causes the higher memory footprint using the other implementations. It might simply be the choice of optimizer. L-BFGS requires more memory than e.g. ADAM which [neural_artistic_style](https://github.com/andersbll/neural_artistic_style) uses.

**Comment by EderSantana** [comment]
Indeed, I just noticed that different optimizer. I'll check it out if that is the case. Thanks for pointing that out.
