### ISSUE TITLE
Penalty calculation

### ISSUE THREAD

**Issue by DmitryUlyanov** [andersbll/deeppy#17]
Hello, are you sure about the sign in these lines ? 
```
if penalty is not None:
            step -= penalty
```
You multiply by `-learn_rate` next to make it `-grad` then at the snippet above `step` should be `grad` and penalty should be added with `+` sign. Is there is something I'm missing ? I've tried to set `weight_decay` to something below zero and this actually makes the weights shrink. If I set `weight_decay` to a large value > 0 then the weights explode.

**Comment by andersbll** [comment]
Wow, this is a huge mistake. Thank you for inspecting the code so thoroughly! Fixed by commit 45cce4efbd94b00de0ba97590e7ea010dac43e68.
