### ISSUE TITLE
where is the nnet module

### ISSUE THREAD

**Issue by by321** [andersbll/deeppy#22]
Hi, 'import deeppy' displayed this error msg:

> File "<ipython-input-1-b89fcff7134a>", line 1, in <module>
>     import deeppy
> 
>   File "C:\Anaconda3\lib\site-packages\deeppy-0.1.dev0-py3.5.egg\deeppy\__init__.py", line 2, in <module>
>     from . import expr
> 
>   File "C:\Anaconda3\lib\site-packages\deeppy-0.1.dev0-py3.5.egg\deeppy\expr\__init__.py", line 18, in <module>
>     import nnet
> 
> ImportError: No module named 'nnet'

Where is this nnet module ?

**Comment by andersbll** [comment]
Hey, thanks for mentioning this. The code was not completely Python 3 compatible. :)
