### ISSUE TITLE
Exception while trying examples

### ISSUE THREAD

**Issue by rcalsaverini** [andersbll/deeppy#5]
Hi, 
I'm trying to run the `convnet_mnist.py` example and I getting an error:

```
INFO     SGD: Model contains 127242 parameters.
INFO     SGD: 469 mini-batch gradient updates per epoch.
terminate called after throwing an instance of 'std::runtime_error'
  what():  src/image/img2win.cu:56: invalid device function 
[1]    10517 abort (core dumped)  python convnet_mnist.py
```

I'm not sure this is a problem with deeppy itselft. It's probably a problem with my cuda installation since I had similar problems trying to run caffe. But as I have no experience with cuda at all, do you guys have any pointers of what might be the issue?

I'll totally understand if you just say "it's a cuda problem, solve it with the cuda guys" , but it also might be something you encountered so...

**Comment by andersbll** [comment]
Closed due to inactivity. Feel free to reopen.
