### ISSUE TITLE
MNIST mlp example fails

### ISSUE THREAD

**Issue by mihaha** [andersbll/deeppy#6]
Using deeppy 0.1 version.

I run run() from 'examples/mlp_mnist.py' and get this:
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-5-157c9bda2cd6> in <module>()
----> 1 run()

<ipython-input-4-87bc676759c6> in run()
     24             dp.FullyConnected(
     25                 n_output=800,
---> 26                 weights=dp.Parameter(dp.AutoFiller(), weight_decay=0.0001),
     27             ),
     28             dp.Activation('relu'),

TypeError: __init__() got an unexpected keyword argument 'weight_decay'
```
removing weight_decay option from dp.Parameter solved an issue.

**Comment by lre** [comment]
It sound like you have an old version of deeppy active. The weight_decay argument has not been there the whole time. Could i get you to try to download en rebuild deeppy and make sure that it is the new build that is active. Hopefully that should fix the issue.

**Comment by andersbll** [comment]
Closed due to inactivity. Feel free to reopen.
